config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users do
    # sessions can manage user
    resources :properties do
      #property show can be a dashboard --
      resources :dashboards, only: [:index]
      resources :rooms
      resources :guests do 
        resources :reservations do 
          resources :occupied_rooms
        end 
      end 
    end 
  end 

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # callbacks --> before action
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :property
  has_many :reservations, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true  
  validates :phone_number, presence: true

  # def current_property
  #   binding.pry
  # end 
end 

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guests = @property.guests.all
  end 

  def show 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find_by(params[:guest_id])
  end
  
  
  def new
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.new
  end 

  def create 
    user = current_user
    property = user.properties.find(params[:property_id])
    guest = property.guests.create!(guest_params)
    guest.save 
    # change this redirect to reservation form later
    redirect_to new_user_property_guest_reservation_path(user, property, guest) 
  end

  def edit
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:id])
  end 

  def update
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:id])
    @guest.update(guest_params)
    @guest.save 
    redirect_to user_property_guests_path(@user, @property) 
  end 

  def destroy
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find_by(params[:guest_id])
    
    @guest.reservations.destroy_all
    @guest.destroy
    redirect_to user_property_dashboards_path(@user, @property)
  end 

  private

  def guest_params 
    params.require(:guest).permit(:first_name, :last_name, :phone_number)
  end 
end

app/views/guests/edit.html.erb
<h1>Edit Guest Information</h1>
<%= form_for [@user, @property, @guest] do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.submit "Submit" %>
<% end %>

app/views/guests/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
    </div>
    <div class="page">
      <h1 class="title">All Guests</h1>
      <% @guests.each do |guest| %>
        <p><%= guest.last_name %>, <%= guest.first_name %></p>
        <p><%= link_to "View Information",  user_property_guest_path(@user, @property, guest)%>
        <p><%= link_to "Edit Guest",  edit_user_property_guest_path(@user, @property, guest)%>
      <% end %>
      <p><%= link_to "Create New Guest", new_user_property_guest_path %></p>
      <p><%= link_to "Back", user_property_path(@user, @property) %></p>
    </div>
  </body>
</html>

app/views/guests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title">Please Enter The Guest Information</h1>
      <%= form_for [@user, @property, @guest] do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
        <%= f.submit "Submit" %>
      <% end %>
    </div>
  </body>
</html>

app/views/guests/show.html.erb
<h1>Page of <%= @guest.first_name %></h1>
<p><%= link_to "View all guests reservations", user_property_guest_reservations_path(@user, @property, @guest) %></p>
<p><%= link_to "Back", user_property_guests_path %></p>
<p><%= button_to "Delete", user_property_guest_path(@user, @property, @guest), method: :delete %>