config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users do
    # sessions can manage user
    resources :properties do
      #property show can be a dashboard --
      resources :dashboards, only: [:index]
      resources :rooms
      resources :guests do 
        resources :reservations do 
          resources :occupied_rooms
        end 
      end 
    end 
  end 

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # callbacks --> before action
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :rooms, dependent: :destroy
  has_many :guests, dependent: :delete_all
  
  validates :name, presence: true
  validates :street, presence: true  
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  validates :phone_number, presence: true
end 

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @user = current_user
    @properties = @user.properties.all
  end 

  def show 
    @user = current_user
    @property = @user.properties.find(params[:id])
    @rooms = @property.rooms 
    
  end 

  def new 
    user = current_user
    @property = user.properties.new
  end 
  
  def create
    user = current_user
    property = user.properties.create!(property_params)
    property.save 
    redirect_to user_property_path(user, property)
  end 

  def edit 
    @user = current_user
    @property = @user.properties.find(params[:id])
  end 

  def update 
    @user = current_user
    @property = @user.properties.find(params[:id])
    @property.update(property_params)
    @property.save 
    redirect_to user_property_path(@user, @property)
  end 

  def destroy 
    @user = current_user
    @property = @user.properties.find(params[:id])
    @property.guests.destroy_all
    @property.destroy
    redirect_to user_properties_path(@user)
  end 

  private

  def property_params
    params.require(:property).permit(:name, :street, :city, :state, :zip_code, :phone_number)
  end 
end

app/views/properties/edit.html.erb
<h1>Please Update Your Property Information</h1>
<%= form_for [@user, @property] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :street %>
  <%= f.text_field :street %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.submit "Update" %>
<% end %>

<p><%= link_to "Back", user_property_path(@user, @property) %>

app/views/properties/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title">All properties</h1>
      <% @properties.each do |property| %>
      <div class="intro">
        <ul><%= link_to property.name, user_property_path(@user, property) %></ul>
     </div>
      <% end %>

<ul><%= link_to "Back", user_path(@user) %></ul>
    </div>
  </body>
</html>

app/views/properties/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title"> Please Enter Your Property Information</h1>
        <%= form_for [@user, @property] do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.label :street %>
          <%= f.text_field :street %>
          <%= f.label :city %>
          <%= f.text_field :city %>
          <%= f.label :state %>
          <%= f.text_field :state %>
          <%= f.label :zip_code %>
          <%= f.text_field :zip_code %>
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number %>

          <%= f.submit "Submit" %>
        <% end %>
        <p><%= link_to "Back", user_path(@user) %></p>
    </div>
  </body>
</html>

app/views/properties/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title"> <%= @property.name.capitalize %></h1>
      <div class="intro">
      <ul><%= link_to "View Rooms",  user_property_rooms_path(@user, @property)%></ul>
      <ul><%= link_to "View All Guests",  user_property_guests_path(@user, @property)%></ul>
      <%if @rooms.empty? %>
      <ul><%= link_to "Your dashboard will be ready when you add rooms and guests",  user_property_rooms_path(@user, @property)%></ul>
      <%elsif @property.guests.empty? %>
      <ul><%= link_to "Your dashboard will be ready when you add rooms and guests",  user_property_guests_path(@user, @property)%></ul>
      <% else %>
      <ul><%= link_to "Dashboard",  user_property_dashboards_path(@user, @property)%></ul>
      <%end %>
      </div>
      <ul><%= link_to "Edit",  edit_user_property_path(@user, @property)%></ul>
      <ul><%= link_to "Back", user_properties_path(@user) %></ul>
      <ul><%= button_to "Delete", user_property_path(@user, @property), method: :delete %></ul>
    </div>
  </body>
</html>