config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users do
    # sessions can manage user
    resources :properties do
      #property show can be a dashboard --
      resources :dashboards, only: [:index]
      resources :rooms
      resources :guests do 
        resources :reservations do 
          resources :occupied_rooms
        end 
      end 
    end 
  end 

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # callbacks --> before action
end

app/models/occupied_room.rb
class OccupiedRoom < ApplicationRecord
  belongs_to :room
  belongs_to :reservation
end 

app/controllers/occupied_rooms_controller.rb
class OccupiedRoomsController < ApplicationController
  def show
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:guest_id])
    @reservation = @guest.reservations.find(params[:reservation_id])
    @occupied_room = @reservation.occupied_rooms.find_by(params[:occupied_room_id])
  end 
  
  def index 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:guest_id])
    @reservation = @guest.reservations.find(params[:reservation_id])
    @occupied_rooms = @reservation.occupied_rooms
  end 
  
  def new
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:guest_id])
    @reservation = @guest.reservations.find(params[:reservation_id])
    @all_rooms = @property.rooms
    @vacant_rooms = @all_rooms.vacant_rooms
    @occupied_room = @reservation.occupied_rooms.new
  end 
  
  def create 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:guest_id])
    @reservation = @guest.reservations.find(params[:reservation_id])
    @occupied_room = @reservation.occupied_rooms.create!(occupied_params)
    if @occupied_room.save
      redirect_to user_property_dashboards_path(@user, @property), notice: 'Room checked in successfully.'
    else 
      redirect_to user_property_guest_reservations_path(@user, @property, @guest), alert: 'Failed to check in room.'
    end 
  end 

  def destroy
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @guest = @property.guests.find(params[:guest_id])
    @reservation = @guest.reservations.find(params[:reservation_id])
    @occupied_room = @reservation.occupied_rooms.find_by(params[:occupied_room_id])
    
    #@guest.reservations.destroy_all
    @occupied_room.destroy
    redirect_to user_property_dashboards_path(@user, @property)
  end 
   private

  def occupied_params
    params.require(:occupied_room).permit(:room_id, :reservation_id)
  end 
end 

app/views/occupied_rooms/index.html.erb
<h1>Occupied Rooms</h1>
<p> Guest: <%= @guest.first_name %> <%= @guest.last_name %></p>
<p> Reservation Date: <%= @reservation.date_in %> to <%= @reservation.date_out %></p>

<% @occupied_rooms.each do |occupied_room| %>
  <p><%= link_to occupied_room.room.room_number, user_property_guest_reservation_occupied_room_path(@user, @property, @guest, @reservation, occupied_room) %></p>
<% end %>

<p><%= link_to 'Check Guest In', new_user_property_guest_reservation_occupied_room_path(@user, @property, @guest, @reservation) %></p>
<p><%= link_to 'Back', user_property_guest_reservation_path(@user, @property, @guest, @reservation) %></p>

app/views/occupied_rooms/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
        
    </div>
    <div class="page">
      <h1 class="title">Check Guest In</h1>
        <%= form_with(model: [@user, @property, @guest, @reservation, @occupied_room], url: user_property_guest_reservation_occupied_rooms_path(@user, @property, @guest, @reservation)) do |form| %>
            <%= form.label :room_id, 'Select a Room to Check In:' %>
            <%= form.collection_select :room_id, @vacant_rooms, :id, :room_number %>
            <%= form.submit 'Check In' %>
        <% end %>
        <p><%= link_to 'Back', user_property_dashboards_path(@user, @property) %></p>
    </div>
  </body>
</html>

app/views/occupied_rooms/show.html.erb
<p><%= @guest.first_name %></p>
<p><%= @occupied_room.room.room_number %></p>
<p><%= @occupied_room.room.room_type %></p>
<%= link_to "Guest Page", user_property_guest_path(@user, @property, @guest)%>
<p><%= link_to "Back", user_property_guest_reservation_occupied_rooms_path(@user, @property, @guest, @reservation) %></p>
<p><%= button_to "Delete", user_property_guest_reservation_occupied_room_path(@user, @property, @guest, @reservation, @occupied_room), method: :delete %></p>