config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users do
    # sessions can manage user
    resources :properties do
      #property show can be a dashboard --
      resources :dashboards, only: [:index]
      resources :rooms
      resources :guests do 
        resources :reservations do 
          resources :occupied_rooms
        end 
      end 
    end 
  end 

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # callbacks --> before action
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :property
  has_many :occupied_rooms, dependent: :delete_all
  
  validates :room_type, presence: true
  validates :price, presence: true  
  # validates :smoking, presence: true
  validates :room_number, presence: true
  validates :vacant, presence: true

  def self.vacant_rooms
    occupied_room_ids = OccupiedRoom.pluck(:room_id)
    Room.where.not(id: occupied_room_ids)
  end 
end 

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @rooms = @property.rooms
  end 
  
  def show 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @room = @property.rooms.find(params[:id])
  end 
  def new
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @room = Room.new
  end 
  
  def create 
    user = current_user
    property = user.properties.find(params[:property_id])
    room = property.rooms.create!(room_params)
    room.save
    redirect_to user_property_path(user, property)
  end 

  def edit 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @room = @property.rooms.find(params[:id])
  end 

  def update 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @room = @property.rooms.find(params[:id])
    @room.update(room_params)
    @room.save 
    redirect_to user_property_room_path(@user, @property, @room)
  end 

  def destroy 
    @user = current_user
    @property = @user.properties.find(params[:property_id])
    @room = @property.rooms.find(params[:id])
    @room.destroy
    redirect_to user_property_rooms_path(@user, @property)
  end 

  private
  def room_params
    params.require(:room).permit(:room_type, :price, :smoking, :count, :room_number)
  end 
end 

app/views/rooms/edit.html.erb
<%= form_for [@user, @property, @room] do |form| %>
  <%= form.label :room_type %>
  <%= form.text_field :room_type %>
  <%= form.label :price %>
  <%= form.text_field :price %>
  <%= form.label :smoking %>
  <%= form.check_box :smoking %>
  <%= form.label :room_number %>
  <%= form.text_field :room_number %>

  <%= form.submit "Update"%>
<% end %>
<p><%= link_to "Back", user_property_room_path(@user, @property, @room) %>

app/views/rooms/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title">All Rooms</h1>
      <% @rooms.each do |room| %>
        <p><%= link_to room.room_type, user_property_room_path(@user, @property, room) %></p>
      <% end %>
      <p><%= link_to "Add Rooms", new_user_property_room_path(@user, @property) %></p>
      <p><%= link_to "Back", user_property_path(@user, @property) %>
    </div>
  </body>
</html>

app/views/rooms/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'header.css' %>
    <%= stylesheet_link_tag 'welcome-style.css' %>
  </head>
  <body>
    <div class="main-header">
        <%= image_tag "pics/logo.png", :class => "logo"%>
        <%= button_to "Logout", sessions_path, method: :delete, :class => "button" %>
    </div>
    <div class="page">
      <h1 class="title">Add A Specific Room</h1>
        <%= form_for [@user, @property, @room] do |form| %>
          <%= form.label :room_type %>
          <%= form.text_field :room_type %>
          <%= form.label :price %>
          <%= form.text_field :price %>
          <%= form.label :smoking %>
          <%= form.check_box :smoking %>
          <%= form.label :room_number %>
          <%= form.text_field :room_number %>

          <%= form.submit "Submit"%>
        <% end %>

        <p><%= link_to "Back", user_property_rooms_path(@user, @property) %>
    </div>
  </body>
</html>

app/views/rooms/show.html.erb
<h1>Room Details</h1>
<p><%= @room.room_type %><p>
<p><%= @room.smoking %><p>
<p><%= @room.room_number %><p>
<p><%= link_to "Edit", edit_user_property_room_path(@user, @property, @room) %><p>
<p><%= link_to "Back", user_property_rooms_path(@user, @property) %></p>
<p><%= button_to "Delete", user_property_room_path(@user, @property, @room), method: :delete %></p>